# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
categories = Category.create([{ name: 'ROLNICTWO'}, { name: 'STOLARSTWO'}, { name: 'OGRODNICTWO'}, { name: 'SPEDYCJA'}, { name: 'MODA'}, { name: 'ELEKTRYKA'}, { name: 'KOMPUTERY'}, { name: 'PLASTYKA'}, { name: 'KANALIZACJA'}, { name: 'METAL'}, { name: 'TOWARY LUKSUSOWE'}, { name: 'BUDOWNICTWO'}, { name: 'HOBBY/DZIECI'}, { name: 'RECYKLING'}, { name: 'FINANSE'}, { name: 'WEGIEL'}])
suffixes = Suffix.create([{ text: 'ex'}, { text: 'eks'}, { text: 'bex'}, { text: 'beks'}, { text: 'rex'}, { text: 'reks'}, { text: 'tex'}, { text: 'teks'}, { text: 'pol'}, { text: 'mar'}, { text: 'bis'}])
@index = 0
Prefix.create(text: 'świn', category: categories[@index])
Prefix.create(text: 'żyt', category: categories[@index])
Prefix.create(text: 'rol', category: categories[@index])
Prefix.create(text: 'corn', category: categories[@index])
Prefix.create(text: 'zboż', category: categories[@index])
Prefix.create(text: 'hodow', category: categories[@index])
Prefix.create(text: 'hodowl', category: categories[@index])
Prefix.create(text: 'krow', category: categories[@index])
Prefix.create(text: 'mlek', category: categories[@index])
Prefix.create(text: 'trzod', category: categories[@index])
Prefix.create(text: 'agro', category: categories[@index])
Prefix.create(text: 'młyn', category: categories[@index])
Prefix.create(text: 'burak', category: categories[@index])
@index = 1
Prefix.create(text: 'stol', category: categories[@index])
Prefix.create(text: 'hebel', category: categories[@index])
Prefix.create(text: 'meblo', category: categories[@index])
Prefix.create(text: 'drew', category: categories[@index])
Prefix.create(text: 'troć', category: categories[@index])
Prefix.create(text: 'drzew', category: categories[@index])
Prefix.create(text: 'strug', category: categories[@index])
Prefix.create(text: 'panel', category: categories[@index])
Prefix.create(text: 'płyt', category: categories[@index])
Prefix.create(text: 'trak', category: categories[@index])
Prefix.create(text: 'płot', category: categories[@index])
Prefix.create(text: 'desk', category: categories[@index])
@index = 2
Prefix.create(text: 'rob', category: categories[@index])
Prefix.create(text: 'łopat', category: categories[@index])
Prefix.create(text: 'traw', category: categories[@index])
Prefix.create(text: 'flor', category: categories[@index])
Prefix.create(text: 'flora', category: categories[@index])
Prefix.create(text: 'grab', category: categories[@index])
Prefix.create(text: 'wiadr', category: categories[@index])
Prefix.create(text: 'wiadro', category: categories[@index])
Prefix.create(text: 'chwast', category: categories[@index])
Prefix.create(text: 'kwiat', category: categories[@index])
Prefix.create(text: 'drzew', category: categories[@index])
@index = 3
Prefix.create(text: 'moto', category: categories[@index])
Prefix.create(text: 'mazut', category: categories[@index])
Prefix.create(text: 'auto', category: categories[@index])
Prefix.create(text: 'benz', category: categories[@index])
Prefix.create(text: 'trans', category: categories[@index])
Prefix.create(text: 'ekspres', category: categories[@index])
Prefix.create(text: 'smar', category: categories[@index])
Prefix.create(text: 'bus', category: categories[@index])
Prefix.create(text: 'diesel', category: categories[@index])
Prefix.create(text: 'car', category: categories[@index])
Prefix.create(text: 'fast', category: categories[@index])
@index = 4
Prefix.create(text: 'but', category: categories[@index])
Prefix.create(text: 'szmat', category: categories[@index])
Prefix.create(text: 'bag', category: categories[@index])
Prefix.create(text: 'toreb', category: categories[@index])
Prefix.create(text: 'skór', category: categories[@index])
Prefix.create(text: 'tekstyl', category: categories[@index])
Prefix.create(text: 'model', category: categories[@index])
Prefix.create(text: 'ciuch', category: categories[@index])
Prefix.create(text: 'sukno', category: categories[@index])
Prefix.create(text: 'weł', category: categories[@index])
Prefix.create(text: 'wełno', category: categories[@index])
Prefix.create(text: 'wełna', category: categories[@index])
Prefix.create(text: 'cotton', category: categories[@index])
Prefix.create(text: 'bluz', category: categories[@index])
Prefix.create(text: 'rajt', category: categories[@index])
@index = 5
Prefix.create(text: 'kabl', category: categories[@index])
Prefix.create(text: 'kabel', category: categories[@index])
Prefix.create(text: 'elektr', category: categories[@index])
Prefix.create(text: 'elektro', category: categories[@index])
Prefix.create(text: 'volt', category: categories[@index])
Prefix.create(text: 'amper', category: categories[@index])
Prefix.create(text: 'prąd', category: categories[@index])
@index = 6
Prefix.create(text: 'cyber', category: categories[@index])
Prefix.create(text: 'tech', category: categories[@index])
Prefix.create(text: 'komp', category: categories[@index])
Prefix.create(text: 'kompu', category: categories[@index])
Prefix.create(text: 'techno', category: categories[@index])
Prefix.create(text: 'kabl', category: categories[@index])
Prefix.create(text: 'kabel', category: categories[@index])
@index = 7
Prefix.create(text: 'art', category: categories[@index])
Prefix.create(text: 'pap', category: categories[@index])
Prefix.create(text: 'paper', category: categories[@index])
Prefix.create(text: 'papier', category: categories[@index])
Prefix.create(text: 'mal', category: categories[@index])
Prefix.create(text: 'malar', category: categories[@index])
Prefix.create(text: 'deco', category: categories[@index])
Prefix.create(text: 'deko', category: categories[@index])
Prefix.create(text: 'decor', category: categories[@index])
Prefix.create(text: 'dekor', category: categories[@index])
Prefix.create(text: 'rys', category: categories[@index])
Prefix.create(text: 'szkic', category: categories[@index])
Prefix.create(text: 'graf', category: categories[@index])
Prefix.create(text: 'grafit', category: categories[@index])
Prefix.create(text: 'grafo', category: categories[@index])
@index = 8
Prefix.create(text: 'rur', category: categories[@index])
Prefix.create(text: 'ruro', category: categories[@index])
Prefix.create(text: 'gaz', category: categories[@index])
Prefix.create(text: 'gazo', category: categories[@index])
Prefix.create(text: 'kanal', category: categories[@index])
Prefix.create(text: 'hydro', category: categories[@index])
Prefix.create(text: 'hydrau', category: categories[@index])
Prefix.create(text: 'akwa', category: categories[@index])
Prefix.create(text: 'aqua', category: categories[@index])
Prefix.create(text: 'plumb', category: categories[@index])
Prefix.create(text: 'zlew', category: categories[@index])
Prefix.create(text: 'szambo', category: categories[@index])
@index = 9
Prefix.create(text: 'śrub', category: categories[@index])
Prefix.create(text: 'śrubo', category: categories[@index])
Prefix.create(text: 'metal', category: categories[@index])
Prefix.create(text: 'spaw', category: categories[@index])
Prefix.create(text: 'cyn', category: categories[@index])
Prefix.create(text: 'cynk', category: categories[@index])
Prefix.create(text: 'miedź', category: categories[@index])
Prefix.create(text: 'hard', category: categories[@index])
Prefix.create(text: 'stop', category: categories[@index])
Prefix.create(text: 'blach', category: categories[@index])
@index = 10
Prefix.create(text: 'wód', category: categories[@index])
Prefix.create(text: 'perfum', category: categories[@index])
Prefix.create(text: 'cygar', category: categories[@index])
Prefix.create(text: 'szlug', category: categories[@index])
Prefix.create(text: 'monopol', category: categories[@index])
Prefix.create(text: 'luks', category: categories[@index])
Prefix.create(text: 'dolar', category: categories[@index])
Prefix.create(text: 'dolaro', category: categories[@index])
Prefix.create(text: 'pew', category: categories[@index])
Prefix.create(text: 'pewex', category: categories[@index])
Prefix.create(text: 'pewexo', category: categories[@index])
@index = 11
Prefix.create(text: 'dźwig', category: categories[@index])
Prefix.create(text: 'dźwigo', category: categories[@index])
Prefix.create(text: 'kop', category: categories[@index])
Prefix.create(text: 'koparko', category: categories[@index])
Prefix.create(text: 'kopar', category: categories[@index])
Prefix.create(text: 'bud', category: categories[@index])
Prefix.create(text: 'budow', category: categories[@index])
Prefix.create(text: 'budowl', category: categories[@index])
Prefix.create(text: 'ceg', category: categories[@index])
Prefix.create(text: 'cegła', category: categories[@index])
Prefix.create(text: 'cegło', category: categories[@index])
Prefix.create(text: 'mur', category: categories[@index])
Prefix.create(text: 'mura', category: categories[@index])
Prefix.create(text: 'beton', category: categories[@index])
Prefix.create(text: 'żelbet', category: categories[@index])
Prefix.create(text: 'majster', category: categories[@index])
Prefix.create(text: 'archi', category: categories[@index])
Prefix.create(text: 'żuraw', category: categories[@index])
Prefix.create(text: 'projekt', category: categories[@index])
Prefix.create(text: 'styropian', category: categories[@index])
Prefix.create(text: 'dacho', category: categories[@index])
Prefix.create(text: 'gont', category: categories[@index])
Prefix.create(text: 'dach', category: categories[@index])
Prefix.create(text: 'remont', category: categories[@index])
Prefix.create(text: 'remonto', category: categories[@index])
Prefix.create(text: 'sanit', category: categories[@index])
Prefix.create(text: 'sanitar', category: categories[@index])
@index = 12
Prefix.create(text: 'hobby', category: categories[@index])
Prefix.create(text: 'krea', category: categories[@index])
Prefix.create(text: 'kreo', category: categories[@index])
Prefix.create(text: 'model', category: categories[@index])
Prefix.create(text: 'zabaw', category: categories[@index])
Prefix.create(text: 'hodow', category: categories[@index])
Prefix.create(text: 'play', category: categories[@index])
Prefix.create(text: 'bobo', category: categories[@index])
Prefix.create(text: 'smyk', category: categories[@index])
Prefix.create(text: 'tyci', category: categories[@index])
Prefix.create(text: 'mamo', category: categories[@index])
Prefix.create(text: 'mama', category: categories[@index])
Prefix.create(text: 'kids', category: categories[@index])
Prefix.create(text: 'plusz', category: categories[@index])
Prefix.create(text: 'maskot', category: categories[@index])
@index = 13
Prefix.create(text: 'odzysk', category: categories[@index])
Prefix.create(text: 'recykl', category: categories[@index])
Prefix.create(text: 'recyklo', category: categories[@index])
Prefix.create(text: 'trasz', category: categories[@index])
Prefix.create(text: 'śmieć', category: categories[@index])
Prefix.create(text: 'śmieci', category: categories[@index])
Prefix.create(text: 'palet', category: categories[@index])
Prefix.create(text: 'śmiet', category: categories[@index])
Prefix.create(text: 'skład', category: categories[@index])
Prefix.create(text: 'wysyp', category: categories[@index])
Prefix.create(text: 'garbag', category: categories[@index])
@index = 14
Prefix.create(text: 'biz', category: categories[@index])
Prefix.create(text: 'dolar', category: categories[@index])
Prefix.create(text: 'złot', category: categories[@index])
Prefix.create(text: 'giełd', category: categories[@index])
Prefix.create(text: 'mamona', category: categories[@index])
Prefix.create(text: 'racho', category: categories[@index])
Prefix.create(text: 'rachun', category: categories[@index])
Prefix.create(text: 'biur', category: categories[@index])
Prefix.create(text: 'biuro', category: categories[@index])
Prefix.create(text: 'giełdo', category: categories[@index])
Prefix.create(text: 'biznes', category: categories[@index])
@index = 15
Prefix.create(text: 'martens', category: categories[@index])
Prefix.create(text: 'ruda', category: categories[@index])
Prefix.create(text: 'kilof', category: categories[@index])
Prefix.create(text: 'węgiel', category: categories[@index])
Prefix.create(text: 'opał', category: categories[@index])
Prefix.create(text: 'piec', category: categories[@index])
Prefix.create(text: 'pieco', category: categories[@index])
Prefix.create(text: 'opało', category: categories[@index])
Prefix.create(text: 'pelet', category: categories[@index])
Prefix.create(text: 'peleto', category: categories[@index])
Prefix.create(text: 'groszek', category: categories[@index])
Prefix.create(text: 'groszko', category: categories[@index])
Prefix.create(text: 'miał', category: categories[@index])
Prefix.create(text: 'miało', category: categories[@index])
Prefix.create(text: 'antracyt', category: categories[@index])
Prefix.create(text: 'kokso', category: categories[@index])
